version: 2.1

aliases:
  - &defaults
    docker:
      - image: circleci/node:12-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
  - &save_npm_cache
    save_cache:
      paths:
        - node_modules
      keys:
        v1-npm-{{ checksum "package-lock.json" }}
  - &restore_npm_cache
    restore_cache:
      keys:
        - v1-npm-{{ checksum "package-lock.json" }}
        - v1-npm-
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "Set up Pip and install requirements"
          command: |
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python get-pip.py
            pip install -r requirements.txt
      - run:
          name:"install npm packages"
          command: |
            npm --production=false ci
      - run:
          name: deploy
          command: |
            echo $CIRCLE_BRANCH
  integration:
    <<: *defaults
    steps:
      - checkout

workflows:
  build-test-deploy:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - circleci-project-setup # remove this before releasing
