version: 2.1

aliases:
  - &defaults
    docker:
      - image: circleci/node:12-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
  - &save_npm_cache
    save_cache:
      paths:
        - node_modules
      keys:
        v1-npm-{{ checksum "package-lock.json" }}
  - restore_npm_cache
    restore_cache:
      keys:
        - v1-npm-{{ checksum "package-lock.json" }}
        - v1-npm-
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run: |
          echo "Setup step is happening here"
          npm --production=false ci
  integration:
    <<: *defaults
    steps:
      - checkout

workflows:
  build-test-deploy:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - circleci-project-setup # remove this before releasing
