version: 2.1

aliases:
  - &defaults
    docker:
      - image: circleci/node:12-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    # working_directory: ~/repo

jobs:
  setup:
    <<: *defaults
    steps:
      - run: echo "Setup step is happening here"


workflows:
  build-test-deploy:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - circleci-project-setup # remove this before releasing
